### PR TITLE
Make proper screenshots for underlying scrollable views

### PR DESCRIPTION
**Pull request by xzenon**
When showing menu above UITableView (or other scrollable view) screenshot is rendered incorrectly if table is scrolled down from the top.
rngridmenuscreenshot

For such case we need to make screenshot based on current table content offset. Added such ability.

### CODE REVIEW

**Comment by rnystrom** [comment]
Would <code>-isMemberOfClass:</code> be better to cover subclasses of <code>UIScrollView</code>?

**Comment by xzenon** [comment]
`-isMemberOfClass:` returns YES if the receiver is an instance of the specified class only while `-isKindOfClass:` returns YES if the receiver is an instance of the specified class or an instance of any class that inherits from the specified class.

I believe `-isKindOfClass:` is exactily what we need to use here.

**Comment by rnystrom** [comment]
Thank you :)

**Comment by xzenon** [comment]
Thank you for a great grid menu! :)

**Pull request merged**
