### PR TITLE
Added pod spec file

### PR DESCRIPTION
**Pull request by thaberkern**
First try of a podspec. Should been working with tags for s.source_files

### CODE REVIEW

**Comment by RobertAudi** [comment]
That's awesome, can't wait for this to get added. One thing to add would be to update the README as well to let people know that there will be a pod.

**Comment by thaberkern** [comment]
@AzizLight You can use it already. Just add the following to your pod file:

pod 'RNGridMenu',  :git => 'https://www.github.com/RtxLabs/RNGridMenu', :commit => '9983a047bd'

**Comment by RobertAudi** [comment]
@thaberkern Ah! That's awesome! Thanks a lot!

**Comment by rnystrom** [comment]
Bam. Thank you! Updating the Readme now.

**Comment by RobertAudi** [comment]
@rnystrom Thanks a lot!

**Pull request merged**
