### PR TITLE
UIBezierPath to exclude from blurring, UIBezierPath to create mask for menu background

### PR DESCRIPTION
**Pull request by myell0w**
Hey, some more additions from my side.

The algorithm for excluding an area from blurring currently is pretty slow, it takes creating 2 images and overlaying them. Since it's optional and off by default I'm still opening the pull request, do you have any idea on how to improve the performance?

### CODE REVIEW

**Comment by rnystrom** [comment]
So I played a little w/ this and am a little confused. Would you mind updating the example with a method that masks the profile image? I tried creating a UIBezierPath with an oval using the image's frame, but nothing seemed to happen. I'm a little unclear what context the path is supposed to use.

**Comment by myell0w** [comment]
Sure, I just added a commit to demonstrate it. You'll notice that when you long-press to show the menu the image isn't blurred.

**Comment by myell0w** [comment]
Hey, any news on this?

**Comment by rnystrom** [comment]
Awesome, thanks for this! :)

**Comment by oneguyindc** [comment]
Hello - How can I add your control to a UIView and not a UIViewController

**Pull request merged**
